// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoZtlOEGEjLUgn4CJG8PZHW1oVMWEXBRo',
    appId: '1:979616910593:android:fad40c7486469a7e9d9f00',
    messagingSenderId: '979616910593',
    projectId: 'aorbo-trek-2a7dd',
    databaseURL: 'https://aorbo-trek-2a7dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aorbo-trek-2a7dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPOpAZ4_J-v4O7CR2Ot2IpUO5j4z0-Fqc',
    appId: '1:979616910593:ios:5f38325b68531c0c9d9f00',
    messagingSenderId: '979616910593',
    projectId: 'aorbo-trek-2a7dd',
    databaseURL: 'https://aorbo-trek-2a7dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aorbo-trek-2a7dd.firebasestorage.app',
    iosBundleId: 'com.eclipso.aroboApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvlmvvlqRr3-ECdwU6FjpNzMqa_Z55d1Q',
    appId: '1:979616910593:web:b2006b40af224de39d9f00',
    messagingSenderId: '979616910593',
    projectId: 'aorbo-trek-2a7dd',
    authDomain: 'aorbo-trek-2a7dd.firebaseapp.com',
    databaseURL: 'https://aorbo-trek-2a7dd-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'aorbo-trek-2a7dd.firebasestorage.app',
    measurementId: 'G-X9P6LM5257',
  );

}